modLoader="javafml"
loaderVersion="[47,)"

license="MIT"
issueTrackerURL="https://github.com/davenonymous/BonsaiTrees/issues"

[[mods]]
modId="bonsaitrees3"
version="${file.jarVersion}"
displayName="Bonsai Trees 3"
displayURL="https://github.com/davenonymous/BonsaiTrees"
logoFile="bonsaitrees_logo.png"
authors="Davenonymous"
description='''
Grow Trees in small pots like Mr. Miyagi!

Some image assets have various Creative Commons license.
You can find a full list in the included licenses.md file in the jar archive.
'''

[[dependencies.bonsaitrees3]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bonsaitrees3]]
    modId="libnonymous"
    mandatory=true
    versionRange="[2.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bonsaitrees3]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"